services:
  - type: web
    name: sortify
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          name: sortify-redis
databases:
  - name: sortify-redis
    plan: free